version: '3.6'

services:
  edge_video_analytics_microservice:
    image: intel/edge_video_analytics_microservice:0.7.2
    container_name: edge_video_analytics_microservice
    environment:
      - ENABLE_WEBRTC=true
      - WEBRTC_SIGNALING_SERVER=ws://${HOST_IP}:8443
      - no_proxy=$no_proxy
      - http_proxy=$http_proxy
      - https_proxy=$https_proxy
      - RUN_MODE=EVA
      - DETECTION_DEVICE=CPU
    depends_on:
      - multimodal-data-visualization-streaming
      - multimodal-data-visualization
    env_file:
      - .env
    ports:
      - ${EVAM_PORT}:${EVAM_PORT}      
    volumes:
      - "./../Edge_Video_Analytics_Resources/pipelines/:/home/pipeline-server/pipelines/"
      - "./../Edge_Video_Analytics_Resources/models:/home/pipeline-server/models/"
      - "./../Edge_Video_Analytics_Resources/resources:/home/pipeline-server/resources/"

  multimodal-data-visualization-streaming:
    image: intel/multimodal-data-visualization-streaming:3.0
    container_name: multimodal-data-visualization-streaming
    hostname: multimodal-data-visualization-streaming
    read_only: true
    restart: unless-stopped
    ipc: "none"
    tmpfs:
      - /etc/nginx/sites-enabled:uid=1999,gid=1999
      - /usr/share/nginx:uid=1999,gid=1999
      - /var/log/nginx:uid=1999,gid=1999
      - /var/cache/nginx:uid=1999,gid=1999
      - /var/lib/nginx:uid=1999,gid=1999
      - /run:uid=1999,gid=1999
    security_opt:
      - no-new-privileges
    environment:
      MODE: "EVA"
    healthcheck:
      test: [ "CMD-SHELL", "exit", "0" ]
      interval: 5m
    env_file:
      - .env
    ports:
      - ${EVA_DEFAULT_PORT}:${EVA_DEFAULT_PORT}
      - ${SIGNALLING_PORT}:${SIGNALLING_PORT}
      - ${EVA_REACT_PORT}:${EVA_REACT_PORT}
  
  multimodal-data-visualization:
    image: intel/multimodal-data-visualization:3.0
    container_name: multimodal-data-visualization
    hostname: multimodal-data-visualization
    read_only: true
    restart: unless-stopped
    ipc: "none"
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    volumes:
       - "vol_temp_grafana:/tmp"
    environment:
      HOST_IP: ${HOST_IP}
      MODE: "EVA"
    env_file:
      - .env
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}

volumes:
  vol_temp_grafana:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
