version: '3.6'

services:
  multimodal-data-visualization-streaming:
    image: intel/multimodal-data-visualization-streaming:3.0
    container_name: multimodal-data-visualization-streaming
    hostname: multimodal-data-visualization-streaming
    read_only: true
    restart: unless-stopped
    ipc: "none"
    tmpfs:
      - /etc/nginx/sites-enabled:uid=1999,gid=1999
      - /usr/share/nginx:uid=1999,gid=1999
      - /var/log/nginx:uid=1999,gid=1999
      - /var/cache/nginx:uid=1999,gid=1999
      - /var/lib/nginx:uid=1999,gid=1999
      - /run:uid=1999,gid=1999
    security_opt:
      - no-new-privileges
    healthcheck:
      test: [ "CMD-SHELL", "exit", "0" ]
      interval: 5m
    env_file:
      - .env
    ports:
      - ${EVA_DEFAULT_PORT}:${EVA_DEFAULT_PORT}
      - ${SIGNALLING_PORT}:${SIGNALLING_PORT}
      - ${EVA_REACT_PORT}:${EVA_REACT_PORT}
         
  multimodal-data-visualization:
    image: intel/multimodal-data-visualization:3.0
    container_name: multimodal-data-visualization
    hostname: multimodal-data-visualization
    read_only: true
    restart: unless-stopped
    ipc: "none"
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    volumes:
       - "vol_temp_grafana:/tmp"
    environment:
      HOST_IP: ${HOST_IP}
    env_file:
      - .env
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}       

volumes:
  vol_temp_grafana:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
